version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: ./gradlew build
